[package]
name = "crisp-runtime"
authors = ["Glenn Wallace <glennw-coding@proton.me>"]
description = "A small, expressive Lisp-inspired programming language."
version = "0.4.1"
edition = "2024"
keywords = ["compiler", "interpreter", "lisp", "programming-language"]
categories = ["compilers", "parser-implementations"]
license = "MIT"
repository = "https://codeberg.org/Stack-Syndicate/crisp"

[dependencies]
